CREATE TABLE "ProductStrategySnapshot" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "marketId" TEXT NOT NULL,
    "researchImportId" TEXT,
    "sourceImportItemId" TEXT,
    "productName" TEXT NOT NULL,
    "businessModel" TEXT NOT NULL DEFAULT '[]',
    "currentProductStage" TEXT NOT NULL,
    "currentValidationStage" TEXT NOT NULL,
    "idealCustomerProfile" TEXT NOT NULL,
    "primaryUser" TEXT NOT NULL,
    "coreProblem" TEXT NOT NULL,
    "productWedge" TEXT NOT NULL,
    "coreWorkflow" TEXT NOT NULL DEFAULT '[]',
    "mvpObjective" TEXT NOT NULL,
    "mvpFeatures" TEXT NOT NULL DEFAULT '[]',
    "notInMvp" TEXT NOT NULL DEFAULT '[]',
    "mvpSuccessCriteria" TEXT NOT NULL DEFAULT '[]',
    "v2Features" TEXT NOT NULL DEFAULT '[]',
    "v3Features" TEXT NOT NULL DEFAULT '[]',
    "longTermPlatformThesis" TEXT NOT NULL,
    "keyProductAssumptions" TEXT NOT NULL DEFAULT '[]',
    "productRisks" TEXT NOT NULL DEFAULT '[]',
    "productReadiness" REAL NOT NULL,
    "pitchReadiness" REAL NOT NULL,
    "commercialValidation" REAL NOT NULL,
    "productValidation" REAL NOT NULL,
    "expansionValidation" REAL NOT NULL,
    "commercialMetricGroups" TEXT NOT NULL DEFAULT '[]',
    "productDecisionStatus" TEXT NOT NULL,
    "buildRoadmap" TEXT NOT NULL DEFAULT '[]',
    "validationGates" TEXT NOT NULL DEFAULT '[]',
    "productActions" TEXT NOT NULL DEFAULT '[]',
    "primaryBlocker" TEXT NOT NULL,
    "rawStrategy" TEXT NOT NULL,
    "approvedBy" TEXT NOT NULL DEFAULT 'Local Researcher',
    "approvedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "ProductStrategySnapshot_marketId_fkey" FOREIGN KEY ("marketId") REFERENCES "Market" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "ProductStrategySnapshot_researchImportId_fkey" FOREIGN KEY ("researchImportId") REFERENCES "ResearchImport" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE UNIQUE INDEX "ProductStrategySnapshot_marketId_key" ON "ProductStrategySnapshot"("marketId");
